Grade by max-scoring submission.
jburns20/Autolab pull request #2
Opened 2018-08-05 00:54 UTC by ncik-roberts

Allow instructor to choose between grading the max-scoring
submission and the latest submission.

I set the default to scoring by max score, since this is what we want in compilers.

The setting is managed on a per-assessment basis, and can be edited from the normal edit-assessment UI.

2018-08-07 22:00 UTC, jburns20 requested changes
Since it isn't clear whether the assessment uses max-score or latest-score grading when looking at the assessment page, we should probably add a line just above the most recent submissions (and at the top of the submission history page) that says which grading scheme is in effect.

The other place we should probably respect the max-submission grading is on the instructor gradesheet page. It would be handy to be able to see everyone's scores at a glance. Updating that might require more work, though.

2018-08-07 22:00 UTC, jburns20 commented on app/models/assessment.rb
> +                 "grade_latest" => false }
We should keep the default as-is (latest score), since this could potentially be merged back into mainline Autolab in the future.

2018-08-23 02:13 UTC, ncik-roberts commented
Sorry, had to force push because I messed something up in the history. The third commit is the one I added since the change request.

The strategy I took was repurposing the `latest_submission` column in the assessments table as the id of the _graded_ submission.

2018-08-23 04:44 UTC, jburns20 approved these changes

2018-08-23 04:45 UTC, merged